import java.io.File
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

plugins {
    java
    id("org.springframework.boot") version "4.1.0"
    id("io.spring.dependency-management") version "1.1.7"
    id("org.hibernate.orm") version "7.4.1.Final"
    id("org.graalvm.buildtools.native") version "1.1.1"
}

group = "win.masteryyh"
version = "0.0.1-SNAPSHOT"
description = "masteryyh-system"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.nimbusds:nimbus-jose-jwt:10.3")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-restclient")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-webmvc")
    implementation("com.github.docker-java:docker-java-core:3.7.1")
    implementation("com.github.docker-java:docker-java-transport-zerodep:3.7.1")
    implementation("org.redisson:redisson-spring-boot-starter:4.5.0")
    implementation("org.bouncycastle:bcprov-jdk18on:1.84")
    implementation("org.bouncycastle:bcpkix-jdk18on:1.84")
    implementation("io.hypersistence:hypersistence-utils-hibernate-73:3.15.3")
    implementation("com.hierynomus:sshj:0.38.0")
    compileOnly("org.projectlombok:lombok")
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    runtimeOnly("org.postgresql:postgresql")
    annotationProcessor("org.projectlombok:lombok")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
}

hibernate {
    enhancement {
    }
}

val buildInfoOutputDir = layout.buildDirectory.dir("generated/sources/buildinfo/main/java")

val generateBuildInfo by tasks.registering {
    description = "Writes build-time version metadata into a generated BuildInfo.java"
    outputs.dir(buildInfoOutputDir)
    // BUILD_TIME changes every run, so always regenerate.
    outputs.upToDateWhen { false }

    doLast {
        val commitHash = runCatching {
            val process = ProcessBuilder("git", "rev-parse", "--short=12", "HEAD")
                .directory(rootDir)
                .redirectErrorStream(true)
                .start()
            if (process.waitFor() == 0) {
                process.inputStream.bufferedReader().readText().trim()
            } else {
                null
            }
        }.getOrNull()?.takeIf { it.isNotBlank() } ?: "unknown"

        val versionEnv = System.getenv("VERSION")?.takeIf { it.isNotBlank() }
        val version = versionEnv ?: "dirty-$commitHash"

        val buildTime = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))

        val packageDir = buildInfoOutputDir.get()
            .dir("win/masteryyh/masteryyhsystem/base/buildinfo")
            .asFile
        packageDir.mkdirs()

        val source = """
            package win.masteryyh.masteryyhsystem.base.buildinfo;

            /**
             * Build-time metadata generated by the Gradle {@code generateBuildInfo} task.
             * Do not edit manually; this file is regenerated on every compile.
             */
            public final class BuildInfo {
                public static final String VERSION = "$version";
                public static final String COMMIT_HASH = "$commitHash";
                public static final String BUILD_TIME = "$buildTime";

                private BuildInfo() {
                }
            }
            """.trimIndent() + "\n"

        File(packageDir, "BuildInfo.java").writeText(source)
    }
}

sourceSets["main"].java.srcDir(generateBuildInfo)
tasks.named("compileJava").configure { dependsOn(generateBuildInfo) }
