server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: masteryyh-system
  datasource:
    url: jdbc:postgresql://truenas.internal.masteryyh.win:5432/masteryyh_test
    username: postgres
    password: abc123456
  data:
    redis:
      redisson:
        file: redisson.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      base-path: "/metrics"
      exposure:
        include: "*"

system:
  jwt-secret: change-this-secret-to-at-least-32-characters
  admin:
    username: admin
    password: abc123456
    email: admin@example.com
